### ISSUE TITLE
Reset ICF-Cache after uploading of an ui5-app

### ISSUE THREAD

**Issue by eugen-eugen** [pfefferf/ui5-nwabap-deployer#12]
Dear maintainers of this nice project,

I use it for deploying of my apps into an abap gateway. 
I found out, that I have to reset the ICF-Cache after an update of an app. Otherwise the changes are not effective, because the  
I do it now by calling **/ui2/invalidate_client_caches** on the gateway.
Ist it possible, that you toll can call  this program optionally after the upload is finished?

Thank you!

JeMo

**Comment by pfefferf** [comment]
Unfortunately the ADT service interface does not provide such a functionality. Therefore it cannot be integrated in this project (because I want to avoid to deliver an own ABAP component as dependency required for this project).

For your custom system, you can create your own service which provides that functionality which you can call using your task runner.
