### ISSUE TITLE
Failing grunt build with new version

### ISSUE THREAD

**Issue by marc4F** [pfefferf/ui5-nwabap-deployer#38]
Hi,

firstly thanks for making that great CI tool!

Since last commit I get the "Connection configuration not (fully) specificed (check server and client)." error.
I'm using the grunt-nwabap-ui5uploader. Maybe I need to add something new to my grunt config?

```
	var config = {
		nwabap_ui5uploader: {
			options: {
				conn: {
					server: abapDevelopmentServerHost
				},
				auth: {
					user: abapDevelopmentUser,
					pwd: abapDevelopmentPassword
				}
			},
			// It uses a already created Transport and package, for deployment.
			upload_build: {
				options: {
					ui5: {
						package: abapPackage,
						bspcontainer: abapApplicationName,
						bspcontainer_text: abapApplicationDesc,
						transportno: abapTransportNumber,
						language: "DE",
						calc_appindex: true
					},
					resources: {
						cwd: targetDir,
						src: "**/*.*"
					}
				}
			}
		}
	};
```

Thanks for the help.

Best regards
Marco

**Comment by pfefferf** [comment]
Hi @marc4F,

issue is solved. In the latest release I fixed that the server information is not checked as mandatory configuration option. I have added such a check for the client too. But that was wrong, because client is not really mandatory ... if not provided the default client will be used (like you assume in your config).

Please update the ui5-nwabap-deployer-core package to the latest version.

Best,
Florian
