### ISSUE TITLE
Use OData service /UI5/ABAP_REPOSITORY_SRV for upload

### ISSUE THREAD

**Issue by stockbal** [pfefferf/ui5-nwabap-deployer#41]
Advantages
- Only delta upload occurs instead of overwriting all files => better for SAP note
- Reduces upload logic as only a zip file of the `dist` folder has to be created as payload

**Comment by pfefferf** [comment]
Hey @stockbal,

thx for bringing that up.

I checked the /UI5/ABAP_REPOSITORY_SRV service some time ago already, but I decided not to use it (in the past, now, in future) because of some incompatibilities and the reason that it is available only since SAP_UI 7.53 (which would mean that users on a lower release - yes, there are still some out there - would not be supported anymore; a support of both endpoints by e.g. a configuration switch is not a goal for me).

But of course the point with the deployment of files which are not changed is relevant. Therefore I implemented a kind of "change detection" in the ui5-nwabap-deployer-core@1.0.21. With that version only files are deployed again for which a content change is detected. 

I hope that helps to reduce the files to deploy for an existing app and to reduce the not necessary stuff collected in a SAP note (by the way, didn't know that the UI5 apps in the food industry are so buggy, that this is relevant :-)).

Cheers,
Florian

**Comment by MatthiasSchmalz** [comment]
Hi @pfefferf,
for longterm I recommend to add the option to use it and maybe switch it as default.
The reason is that the service should become the new standard way for deployment and also introduces additional sanity checks, which are not possible with the other API.
Therefore the team provider API is being deprecated (but not shut down because some tools still use it).

Best regards
Matthias

**Comment by pfefferf** [comment]
@MatthiasSchmalz @stockbal 
Version 2.0.0 released today covers that topic.
Starting from version 2.0.0 all toolings use the /UI5/ABAP_REPOSITORY_SRV OData service for deployment. Team Provider API support is removed. For all "legacy" systems version 1.x.x of the toolings still can be used (and maintained).

**Comment by silkearians** [comment]
Great - thanks a lot
